routes/web.php
<?php

use Illuminate\Support\Facades\Route;
use App\Http\Controllers\appointmentController;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('pages.welcome');
});

Auth::routes();
Route::get('/home', 'HomeController@index')->name('home');
Route::post('/search', 'HomeController@search')->name('search');

Route::group(['middleware' => 'auth', 'prefix' => 'department', 'as' => 'department.'], function () {
    Route::get('/create', ['as' => 'get', 'uses' => 'HomeController@createDepartment']);
    Route::post('/create', ['as' => 'create', 'uses' => 'HomeController@setDepartment']);
    Route::get('/assign',  ['as' => 'assign', 'uses' => 'HomeController@assignDepartmentView']);
    Route::put('/assign', ['as' => 'update', 'uses' => 'HomeController@assignDepartment']);
});

Route::group(['prefix' => 'appointment', 'as' => 'appointment.'], function () {
    Route::get('/', ['as' => 'get', 'uses' => 'appointmentController@index']);
    Route::post('/', ['as' => 'create', 'uses' => 'appointmentController@createAppointment']);
    Route::group(['middleware' => 'auth'], function () {
        Route::get('/{id}', ['as' => 'details', 'uses' => 'appointmentController@getDetail']);
        Route::put('/', ['as' => 'update', 'uses' => 'appointmentController@updateAppointment']);
    });
});

Route::group(['middleware' => 'auth', 'prefix' => 'confirmAppointment', 'as' => 'confirm.'], function () {
    Route::get('/{id}', ['as' => 'details', 'uses' => 'appointmentController@getConfirmDetail']);
    Route::put('/', ['as' => 'update', 'uses' => 'appointmentController@setConfirmDetail']);
});

Route::group(['middleware' => 'auth', 'prefix' => 'appointmentDoc', 'as' => 'docComfirm.'], function () {
    Route::get('/{id}', ['as' => 'details', 'uses' => 'appointmentController@getDetailDoc']);
    Route::put('/', ['as' => 'update', 'uses' => 'appointmentController@updatePatientStatus']);
});

resources/views/layouts/app.blade.php
<!doctype html>
<html lang="{{ str_replace('_', '-', app()->getLocale()) }}">

<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <!-- CSRF Token -->
    <meta name="csrf-token" content="{{ csrf_token() }}">

    <title>Hospital Appointment System</title>

    <!-- Scripts -->
    <script src="{{ asset('js/app.js') }}" defer></script>

    <!-- Fonts -->
    <link rel="dns-prefetch" href="//fonts.gstatic.com">
    <link href="https://fonts.googleapis.com/css?family=Nunito" rel="stylesheet">

    <!-- Styles -->
    <link href="{{ asset('css/app.css') }}" rel="stylesheet">
    @yield('head')
</head>

<body>
    <div id="app">
        <nav class="navbar navbar-expand-md navbar-light bg-white shadow-sm">
            <div class="container">
                <a class="navbar-brand" href="{{ url('/') }}">
                    Hospital Appointment System
                </a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="{{ __('Toggle navigation') }}">
                    <span class="navbar-toggler-icon"></span>
                </button>

                <div class="collapse navbar-collapse" id="navbarSupportedContent">
                    <!-- Left Side Of Navbar -->
                    <ul class="navbar-nav mr-auto">

                    </ul>

                    <!-- Right Side Of Navbar -->
                    <ul class="navbar-nav ml-auto">
                        <!-- Authentication Links -->
                        @guest
                        <li class="nav-item">
                            <a class="nav-link" href="{{ route('login') }}">{{ __('Login') }}</a>
                        </li>
                        @if (Route::has('register'))
                        <li class="nav-item">
                            <a class="nav-link" href="{{ route('register') }}">{{ __('Register') }}</a>
                        </li>
                        @endif
                        @else
                        <li class="nav-item dropdown">
                            <a id="navbarDropdown" class="nav-link dropdown-toggle" href="#" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false" v-pre>
                                {{ Auth::user()->name }}
                            </a>

                            <div class="dropdown-menu dropdown-menu-right" aria-labelledby="navbarDropdown">
                                <a class="dropdown-item" href="{{ route('logout') }}" onclick="event.preventDefault();
                                                     document.getElementById('logout-form').submit();">
                                    {{ __('Logout') }}
                                </a>

                                <form id="logout-form" action="{{ route('logout') }}" method="POST" class="d-none">
                                    @csrf
                                </form>
                            </div>
                        </li>

                        @if(Auth::user()->userType == 'doctor')
                        <li class="nav-item">
                            <a class="nav-link" href="{{ route('department.get') }}">Create Department</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" href="{{ route('department.assign') }}">Assign Department</a>
                        </li>
                        @endif
                        @endguest
                    </ul>
                </div>
            </div>
        </nav>

        <main class="py-4">
            @yield('content')
        </main>
    </div>
</body>

</html>