routes/web.php
<?php

use Illuminate\Support\Facades\Route;
use App\Http\Controllers\appointmentController;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('pages.welcome');
});

Auth::routes();
Route::get('/home', 'HomeController@index')->name('home');
Route::post('/search', 'HomeController@search')->name('search');

Route::group(['middleware' => 'auth', 'prefix' => 'department', 'as' => 'department.'], function () {
    Route::get('/create', ['as' => 'get', 'uses' => 'HomeController@createDepartment']);
    Route::post('/create', ['as' => 'create', 'uses' => 'HomeController@setDepartment']);
    Route::get('/assign',  ['as' => 'assign', 'uses' => 'HomeController@assignDepartmentView']);
    Route::put('/assign', ['as' => 'update', 'uses' => 'HomeController@assignDepartment']);
});

Route::group(['prefix' => 'appointment', 'as' => 'appointment.'], function () {
    Route::get('/', ['as' => 'get', 'uses' => 'appointmentController@index']);
    Route::post('/', ['as' => 'create', 'uses' => 'appointmentController@createAppointment']);
    Route::group(['middleware' => 'auth'], function () {
        Route::get('/{id}', ['as' => 'details', 'uses' => 'appointmentController@getDetail']);
        Route::put('/', ['as' => 'update', 'uses' => 'appointmentController@updateAppointment']);
    });
});

Route::group(['middleware' => 'auth', 'prefix' => 'confirmAppointment', 'as' => 'confirm.'], function () {
    Route::get('/{id}', ['as' => 'details', 'uses' => 'appointmentController@getConfirmDetail']);
    Route::put('/', ['as' => 'update', 'uses' => 'appointmentController@setConfirmDetail']);
});

Route::group(['middleware' => 'auth', 'prefix' => 'appointmentDoc', 'as' => 'docComfirm.'], function () {
    Route::get('/{id}', ['as' => 'details', 'uses' => 'appointmentController@getDetailDoc']);
    Route::put('/', ['as' => 'update', 'uses' => 'appointmentController@updatePatientStatus']);
});

resources/views/pages/MakeAppointment.blade.php
<!doctype html>
<html lang="{{ str_replace('_', '-', app()->getLocale()) }}">

<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <!-- CSRF Token -->
    <meta name="csrf-token" content="{{ csrf_token() }}">

    <title>Hospital Appointment System</title>

    <!-- Scripts -->
    <script src="{{ asset('js/app.js') }}" defer></script>

    <!-- Fonts -->
    <link rel="dns-prefetch" href="//fonts.gstatic.com">
    <link href="https://fonts.googleapis.com/css?family=Nunito" rel="stylesheet">

    <!-- Styles -->
    <link href="{{ asset('css/app.css') }}" rel="stylesheet">
    <link href="{{ asset('css/makeAppointment.css')}}" rel="stylesheet" />

    <link href="https://unpkg.com/gijgo@1.9.13/css/gijgo.min.css" rel="stylesheet" type="text/css" />
</head>

<body>
    <div id="makeAppointment">
        <div class="container">
            <div class="row no-gutters justify-content-center">
                <div class="col-xl-8">
                    <div class="card">
                        <div class="card-hearder">
                            <h3 class="form-title ">Appointment Form</h3>
                        </div>
                        <div class="card-body">
                            {{ Form::open(array('route'=> 'appointment.create'))}}
                            <div class="row">
                                <div class="col-md">
                                    {{ Form::label('name', "*Name: ")}}
                                    {{ Form::text('name', null, array('placeholder'=>'Example: Name as IC', 'class'=>'contentInput')) }}
                                    @if ($errors->has('name'))
                                    <p class="error">{{ $errors->first('name') }}</p>
                                    @endif
                                </div>
                                <div class="col-md">
                                    {{ Form::label('mobile', '*Mobile Number:')}}
                                    {{ Form::text('mobile', null, ['placeholder'=>'Example: 0161234567','class'=>'contentInput'])}}
                                    @if ($errors->has('mobile'))
                                    <p class="error">{{ $errors->first('mobile') }}</p>
                                    @endif
                                </div>
                            </div>
                            <div class="row pt-3">
                                <div class="col-md">
                                    {{ Form::label('ic', '*IC Number: (without "-")')}}
                                    {{ Form::text('ic', null, ['placeholder'=>'Example: 123456121234','class'=>'contentInput'])}}
                                    @if ($errors->has('ic'))
                                    <p class="error">{{ $errors->first('ic') }}</p>
                                    @endif
                                </div>
                                <div class="col-md">
                                    {{ Form::label('email', "*Email Address: ")}}
                                    {{ Form::email('email', null, array('placeholder'=>'Example: abc@gmail.com','class'=>'contentInput')) }}
                                    @if ($errors->has('email'))
                                    <p class="error">{{ $errors->first('email') }}</p>
                                    @endif

                                </div>
                            </div>
                            <div class="row pt-3">
                                <div class="col-md">
                                    {{ Form::label('appointmentDate', "*Appointment Date: ")}}
                                    {{ Form::text('appointmentDate', null, array('placeholder'=>'Example: 1/25/2021', 'id'=>'datepicker')) }}
                                    @if ($errors->has('appointmentDate'))
                                    <p class="error">{{ $errors->first('appointmentDate') }}</p>
                                    @endif
                                </div>
                            </div>
                            <div class="row pt-3">
                                <div class="col-md">
                                    {{ Form::label('symptom', "*Symptom: ")}}
                                    {{ Form::textarea('symptom', null, array('class'=>'contentInput')) }}
                                    @if ($errors->has('symptom'))
                                    <p class="error">{{ $errors->first('symptom') }}</p>
                                    @endif
                                </div>
                            </div>
                            <div class="row pt-3 ">
                                <div class="col-md-10"></div>

                                <div class="col-md-2 d-flex justify-content-end">
                                    {{ Form::submit('Submit', array('class'=>'btn-submit'))}}
                                </div>
                                {{ Form::close()}}
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
    </div>
    <script src="{{ asset('js/app.js') }}"></script>
    <script src="https://unpkg.com/gijgo@1.9.13/js/gijgo.min.js" type="text/javascript"></script>
    <script>
        $('#datepicker').datepicker({
            uiLibrary: 'bootstrap4'
        });
    </script>

</body>

</html>

resources/views/pages/assignDepartment.blade.php
@extends('layouts.app')
@section('head')
<link href="{{ asset('css/makeAppointment.css')}}" rel="stylesheet" />
@endsection
@section('content')
<div class="container">
    <div id="makeAppointment">
        <div class="row no-gutters justify-content-center">
            <div class="col-xl-8">
                <div class="card">
                    <div class="card-hearder">
                        <h3 class="form-title ">Appointment Details</h3>
                    </div>
                    <div class="card-body">
                        {{ Form::open(array('route'=> 'department.update', 'method' => 'PUT'))}}
                        <div class="row no-gutters">
                            <div class="col-xl-3"></div>
                            <div class="col-xl-3">
                                <p>Doctor Name: </p>
                            </div>
                            <div class="col-xl-6">
                                <p>{{ $doctor->name }}</p>
                            </div>
                        </div>
                        <div class="row no-gutters">
                            <div class="col-xl-3"></div>
                            <div class="col-xl-3">
                                <p>Patient Status: </p>
                            </div>
                            <div class="col-xl-5">
                                {{ Form::hidden('id',  $doctor->doctorID)}}
                                {{ Form::select('department', $department, null, ['class'=>'contentInput'])}}
                            </div>
                        </div>
                        <div class="row pt-3 ">
                            <div class="col-md-4"></div>
                            <div class="col-md-4 ">
                                {{ Form::submit('Submit', array('class'=>'btn-submit'))}}
                            </div>

                        </div>
                        {{ Form::close()}}
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
@endsection

resources/views/pages/confirmAppointment.blade.php
@extends('layouts.app')
@section('head')
<link href="{{ asset('css/details.css') }}" rel="stylesheet" type="text/css" />
@endsection
@section('content')
<div class="container">
    <div id="details">
        <div class="row no-gutters justify-content-center">
            <div class="col-xl-8">
                <div class="card">
                    <div class="card-hearder">
                        <h3 class="form-title ">Appointment Details</h3>
                    </div>
                    <div class="card-body">
                        @foreach($lists as $list)

                        <div class="row no-gutters">
                            <div class="col-xl-3"></div>
                            <div class="col-xl-4">
                                <p>Appointment Code: </p>
                            </div>
                            <div class="col-xl-5">
                                <p>{{ $list->appointmentCode }}</p>
                            </div>
                        </div>
                        <div class="row no-gutters">
                            <div class="col-xl-3"></div>
                            <div class="col-xl-4">
                                <p>Appointment Date: </p>
                            </div>
                            <div class="col-xl-5">
                                <p>{!! $list->appointmentDate !!}</p>
                            </div>
                        </div>
                        <div class="row no-gutters">
                            <div class="col-xl-3"></div>
                            <div class="col-xl-4">
                                <p>Appointment Status: </p>
                            </div>
                            <div class="col-xl-5">
                                <p>{!! $list->status !!}</p>
                            </div>
                        </div>
                        <div class="row no-gutters">
                            <div class="col-xl-3"></div>
                            <div class="col-xl-4">
                                <p>Patient Name: </p>
                            </div>
                            <div class="col-xl-5">
                                <p>{{ $list->patients->name }}</p>
                            </div>
                        </div>
                        <div class="row no-gutters">
                            <div class="col-xl-3"></div>
                            <div class="col-xl-4">
                                <p>IC Number: </p>
                            </div>
                            <div class="col-xl-5">
                                <p>{!! $list->patients->IC !!}</p>
                            </div>
                        </div>
                        <div class="row no-gutters">
                            <div class="col-xl-3"></div>
                            <div class="col-xl-4">
                                <p>Email: </p>
                            </div>
                            <div class="col-xl-5">
                                <p>{!! $list->patients->email !!}</p>
                            </div>
                        </div>
                        <div class="row no-gutters">
                            <div class="col-xl-3"></div>
                            <div class="col-xl-4">
                                <p>Phone Number: </p>
                            </div>
                            <div class="col-xl-5">
                                <p>{!! $list->patients->mobile !!}</p>
                            </div>
                        </div>
                        <div class="row no-gutters">
                            <div class="col-xl-3"></div>
                            <div class="col-xl-4">
                                <p>Doctor: </p>
                            </div>
                            <div class="col-xl-5">
                                <p>{!! $list->doctors->name !!}</p>
                            </div>
                        </div>
                        @endforeach
                        {{ Form::open(array('route' => 'confirm.update', 'method' => 'PUT')) }}
                        {{ Form::hidden('id', $list->id)}}
                        <div class="row no-gutters">
                            <div class="col-xl-3"></div>
                            <div class="col-xl-4">
                                {{ Form::submit('Confirm', array('class'=>'btn-submit'))}}
                            </div>
                            {{ Form::close()}}
                            <div class="col-xl-5">
                                <a href="{{ route('home') }}"><button class="btn-back">Back</button></a>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
@endsection

resources/views/pages/createDepartment.blade.php
@extends('layouts.app')
@section('head')
<link href="{{ asset('css/makeAppointment.css')}}" rel="stylesheet" />
@endsection
@section('content')
<div class="container">
    <div id="makeAppointment">
        <div class="row no-gutters justify-content-center">
            <div class="col-xl-8">
                <div class="card">
                    <div class="card-hearder">
                        <h3 class="form-title ">Create Department</h3>
                    </div>
                    <div class="card-body">
                        {{ Form::open(array('route'=> 'department.create'))}}
                        <div class="row">
                            <div class="col-md-12">
                                {{ Form::label('name', "*Department Name: ")}}
                                {{ Form::text('name', null, array('placeholder'=>'Example:Special Department', 'class'=>'contentInput')) }}
                                @if ($errors->has('name'))
                                <p class="error">{{ $errors->first('name') }}</p>
                                @endif
                            </div>
                        </div>

                        <div class="row">
                            <div class="col-md-4"></div>
                            <div class="col-md-4">
                                {{ Form::submit('Submit', array('class'=>'btn-submit'))}}
                            </div>
                            <div class="col-md-4"></div>
                        </div>
                        {{ Form::close()}}
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
@endsection

resources/views/pages/details.blade.php
@extends('layouts.app')
@section('head')
<link href="{{ asset('css/details.css') }}" rel="stylesheet" type="text/css" />
@endsection
@section('content')
<div class="container">
    <div id="details">
        <div class="row no-gutters justify-content-center">
            <div class="col-xl-8">
                <div class="card">
                    <div class="card-hearder">
                        <h3 class="form-title ">Appointment Details</h3>
                    </div>
                    <div class="card-body">
                        @foreach($lists as $list)

                        <div class="row no-gutters">
                            <div class="col-xl-3"></div>
                            <div class="col-xl-4">
                                <p>Appointment Code: </p>
                            </div>
                            <div class="col-xl-5">
                                <p>{{ $list->appointmentCode }}</p>
                            </div>
                        </div>
                        <div class="row no-gutters">
                            <div class="col-xl-3"></div>
                            <div class="col-xl-4">
                                <p>Appointment Date: </p>
                            </div>
                            <div class="col-xl-5">
                                <p>{!! $list->appointmentDate !!}</p>
                            </div>
                        </div>
                        <div class="row no-gutters">
                            <div class="col-xl-3"></div>
                            <div class="col-xl-4">
                                <p>Appointment Status: </p>
                            </div>
                            <div class="col-xl-5">
                                <p>{!! $list->status !!}</p>
                            </div>
                        </div>
                        <div class="row no-gutters">
                            <div class="col-xl-3"></div>
                            <div class="col-xl-4">
                                <p>Patient Name: </p>
                            </div>
                            <div class="col-xl-5">
                                <p>{{ $list->patients->name }}</p>
                            </div>
                        </div>
                        <div class="row no-gutters">
                            <div class="col-xl-3"></div>
                            <div class="col-xl-4">
                                <p>IC Number: </p>
                            </div>
                            <div class="col-xl-5">
                                <p>{!! $list->patients->IC !!}</p>
                            </div>
                        </div>
                        <div class="row no-gutters">
                            <div class="col-xl-3"></div>
                            <div class="col-xl-4">
                                <p>Email: </p>
                            </div>
                            <div class="col-xl-5">
                                <p>{!! $list->patients->email !!}</p>
                            </div>
                        </div>
                        <div class="row no-gutters">
                            <div class="col-xl-3"></div>
                            <div class="col-xl-4">
                                <p>Phone Number: </p>
                            </div>
                            <div class="col-xl-5">
                                <p>{!! $list->patients->mobile !!}</p>
                            </div>
                        </div>
                        <div class="row no-gutters">
                            <div class="col-xl-3"></div>
                            <div class="col-xl-4">
                                <p>Symptom: </p>
                            </div>
                            <div class="col-xl-5">
                                <p>{!! $list->symptom !!}</p>
                            </div>
                        </div>
                        @endforeach
                        {{ Form::open(array('route' => 'appointment.update', 'method' => 'PUT')) }}
                        
                        <div class="row no-gutters">
                            <div class="col-xl-3"></div>
                            <div class="col-xl-4">
                                <p>Doctor: </p>
                            </div>
                            <div class="col-xl-5">
                                {{ Form::hidden('id', $list->id)}}
                                {{ Form::select('doctor', $doctors ,null, ['class'=>'contentInput'])}}
                            </div>
                        </div>
                        <div class="row no-gutters">
                            <div class="col-xl-3"></div>
                            <div class="col-xl-4">
                                {{ Form::submit('Submit', array('class'=>'btn-submit'))}}
                            </div>
                            {{ Form::close()}}
                            <div class="col-xl-5">
                                <a href="{{ route('home') }}"><button class="btn-back">Back</button></a>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
@endsection

resources/views/pages/detailsDoc.blade.php
@extends('layouts.app')
@section('head')
<link href="{{ asset('css/details.css') }}" rel="stylesheet" type="text/css" />
@endsection
@section('content')
<div class="container">
    <div id="details">
        <div class="row no-gutters justify-content-center">
            <div class="col-xl-8">
                <div class="card">
                    <div class="card-hearder">
                        <h3 class="form-title ">Appointment Details</h3>
                    </div>
                    <div class="card-body">
                        @foreach($lists as $list)

                        <div class="row no-gutters">
                            <div class="col-xl-3"></div>
                            <div class="col-xl-4">
                                <p>Appointment Code: </p>
                            </div>
                            <div class="col-xl-5">
                                <p>{{ $list->appointmentCode }}</p>
                            </div>
                        </div>
                        <div class="row no-gutters">
                            <div class="col-xl-3"></div>
                            <div class="col-xl-4">
                                <p>Appointment Date: </p>
                            </div>
                            <div class="col-xl-5">
                                <p>{!! $list->appointmentDate !!}</p>
                            </div>
                        </div>

                        <div class="row no-gutters">
                            <div class="col-xl-3"></div>
                            <div class="col-xl-4">
                                <p>Patient Name: </p>
                            </div>
                            <div class="col-xl-5">
                                <p>{{ $list->patients->name }}</p>
                            </div>
                        </div>
                        <div class="row no-gutters">
                            <div class="col-xl-3"></div>
                            <div class="col-xl-4">
                                <p>IC Number: </p>
                            </div>
                            <div class="col-xl-5">
                                <p>{!! $list->patients->IC !!}</p>
                            </div>
                        </div>
                        <div class="row no-gutters">
                            <div class="col-xl-3"></div>
                            <div class="col-xl-4">
                                <p>Email: </p>
                            </div>
                            <div class="col-xl-5">
                                <p>{!! $list->patients->email !!}</p>
                            </div>
                        </div>
                        <div class="row no-gutters">
                            <div class="col-xl-3"></div>
                            <div class="col-xl-4">
                                <p>Phone Number: </p>
                            </div>
                            <div class="col-xl-5">
                                <p>{!! $list->patients->mobile !!}</p>
                            </div>
                        </div>
                        <div class="row no-gutters">
                            <div class="col-xl-3"></div>
                            <div class="col-xl-4">
                                <p>Symptom: </p>
                            </div>
                            <div class="col-xl-5">
                                <p>{!! $list->symptom !!}</p>
                            </div>
                        </div>
                        @endforeach
                        {{ Form::open(array('route' => 'docComfirm.update', 'method' => 'PUT')) }}
                        <div class="row no-gutters">
                            <div class="col-xl-3"></div>
                            <div class="col-xl-4">
                                <p>Patient Status: </p>
                            </div>
                            <div class="col-xl-5">
                                {{ Form::hidden('id', $list->patients->patientID)}}
                                {{ Form::select('status', ['pending'=> 'Pending', 'done'=>"Done"],$list->patients->appointment_status, ['class'=>'contentInput'])}}
                            </div>
                        </div>
                        <div class="row no-gutters">
                            <div class="col-xl-3"></div>
                            <div class="col-xl-4">
                                {{ Form::submit('Submit', array('class'=>'btn-submit'))}}
                            </div>
                            {{ Form::close()}}
                            <div class="col-xl-5">
                                <a href="{{ route('home') }}"><button class="btn-back">Back</button></a>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
@endsection

resources/views/pages/home.blade.php
@extends('layouts.app')
@section('head')
<link href="{{ asset('css/home.css') }}" rel="stylesheet" type="text/css" />
<link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.1.0/css/all.css" integrity="sha384-lKuwvrZot6UHsBSfcMvOkWwlCMgc0TaWr+30HWe3a4ltaBwTZhyTEggF5tJv8tbt" crossorigin="anonymous">
@endsection
@section('content')
<div class="container">
<div class="row justify-content-end">
        <div class="col-md-4 col-md-offset-3">
            <form action="{{ route('search') }}" method="POST" class="search-form">
                @csrf
                <div class="form-group has-feedback">
            		<label for="search" class="sr-only">Search</label>
            		<input type="text" class="form-control" name="search" id="search" placeholder="Search">
                    <i class="fas fa-search form-control-feedback"></i>
            	</div>
            </form>
        </div>
    </div>
    <div class="row justify-content-center">
        <div class="col-md-8">
            <table class="table">
                <thead>
                    <tr>
                        <th scope="col">#</th>
                        <th scope="col">Appointment Code</th>
                        <th scope="col">Patient Name</th>
                        <th scope="col">Status</th>
                        <th scope="col">Action</th>
                    </tr>
                </thead>
                <tbody>
                    @foreach($lists as $list)
                    <tr>
                        <th scope="row">{{ $list->id }}</th>
                        <td>{{ $list->appointmentCode}}</td>
                        <td>{{ $list->patients->name }}</td>
                        @if($userType == 'nurse')
                        <td>{{ $list->status}}</td>
                        @if($list->status != 'done')
                        <td><a href="{{ route('appointment.details', $list->id) }}"><button class="btn-submit full">Update</button></a></td>
                        @if($list->doctorID != null)
                        <td><a href="{{ route('confirm.details', $list->id) }}"><button class="btn-submit full">Confirm</button></a></td>
                        @endif
                        @endif
                        @elseif($userType == 'doctor')
                        <td>{{ $list->patients->appointment_status}}</td>
                        <td><a href="{{ route('docComfirm.details', $list->id) }}"><button class="btn-submit">Update</button></a></td>
                        @endif
                    </tr>
                    @endforeach
                </tbody>
            </table>
        </div>
    </div>
</div>

@endsection